---
layout: post
title: "2021년 05월 03일 공부일지"
image:
categories: [회고]
tags: 
  - 
sitemap:
  changefreq: daily
  priority: 1.0
---

## 오늘 공부한 내용

- ARC와 Memory Structure

  - ARC는 자동으로 Reference count를 관리하는 기능
  - Memory Structure에는 Code, Data, Stack, Heap 영역이 있다

- Retain Cycle과 Dead Lock

  - Retain Cycle의 예시를 볼 수 있는 App (godrm님의 프로젝트) [링크](https://github.com/godrm/RetainCycleApp)
  - ARC 공식문서의 Strong retain cycle에 대해

- 참조타입이랑 값타입이랑 뭐가 다르지?

- retain count는 누가 관리해주지?

- retain count를 관리해주는 애들은 모두 heap에 간다!

- 값타입이 선호되는 이유 (성능에 왜 유리할까)

- catch문에 error를 변수로 선언해서 쓰는 방법

- https://nshipster.com/swift-foundation-error-protocols/

- extension 에다가만 protocol 채택해서 쓰는것 그냥 처음부터 채택하는거랑 뭐가 다르지?

  - 이미 구현되어있는 애에다가 프로토콜을 주입할 수 있음 (의존성 주입)

- 이게 왜 되는거지? 

  ```swift
  mutating func closeBank(totalCustomerNumber: Int?) throws {
          closeTime = CFAbsoluteTimeGetCurrent()
          let spentTime = try getSpentTime()
          
          guard let numberOfCustomers = totalCustomerNumber else {
              throw BankManagerError.failToGetTotalCustomerNumber
          }
          
          print("업무가 마감되었습니다. 오늘 업무를 처리한 고객은 총 \(numberOfCustomers)명이며, 총 업무시간은 \(spentTime)초입니다.")
      }
      
      private func getSpentTime() throws -> String {
          guard let open = openTime,
                let close = closeTime else {
              throw BankManagerError.failToCaclulateSpentTime
          }
          
          let spentTime = formatTimeDuration(time: open - close)
          return spentTime
      }
  ```

  왜 try에 do - catch가 없는데도 정상 동작할까? -> Error Description을 자동으로 String으로 바꿔주는건가? 흠...

- setUp, tearDown을 쓰는 이유

  - 메모리를 위해서
  - 

병렬성은 같은 작업을 여러개의 CPU가 동시에 하는 것

우리가 하는 것은 여러개의 '다른' 작업이기 때문에 동시성 프로그래밍이다 (병렬성 아님)

코어가 여러개 일때만 병렬 프로그래밍이 가능하다.